name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.13.2
          
      - name: Build the docker-compose database
        run: |
          docker-compose up -d --build database
          docker-compose ps -a
        
      - name: Build the docker-compose server
        run: |
          docker-compose up -d --build server
          docker-compose ps -a
          
      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        
      - name: Install client dependencies
        run: npm install
        working-directory: client
        
      - name: Run client test
        run: npm run test
        working-directory: client
        
      - name: Stop docker-compose containers
        if: always()
        run: docker-compose down
      
        
