name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
      - uses: actions/checkout@v2
      
      - name: Docker-Compose
        run: docker-compose up -d
        
